name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t tristanrobert/nmap-docker:${{ github.sha }} .

      - name: Lint docker file
        uses: hands-lab/dockle-action@v1
        with:
          image: 'tristanrobert/nmap-docker:${{ github.sha }}'
          exit-code: '1'
          exit-level: FATAL
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tristanrobert/nmap-docker:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Publish latest image to Dockerhub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
          docker tag tristanrobert/nmap-docker:${{ github.sha }} tristanrobert/nmap-docker:latest
          docker push tristanrobert/nmap-docker:latest
